---
version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gha-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    groups:
      npm-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: monthly
    groups:
      pip-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
