---
- name: "A-build"
  color: "f7e101"
  description: "Area: CI build infrastructure."
- name: "A-codesigning"
  color: "f7e101"
  description: "Area: Code signing, GPG signatures."
- name: "A-deps"
  color: "f7e101"
  description: "Area: Source and library dependencies."
- name: "A-performance"
  color: "f7e101"
  description: "Area: Performance improvements and optimizations."
- name: "A-project"
  color: "f7e101"
  description: "Area: Infrastructure for running an open source project."
- name: "A-release"
  color: "f7e101"
  description: "Area: Nightly releases and version bumps."
- name: "A-security"
  color: "f7e101"
  description: "Area: Security vulnerabilities and unsoundness issues."
- name: "A-target"
  color: "f7e101"
  description: "Area: nightly build support for various target triples."
- name: "C-bug"
  color: "c1c8ff"
  description: "Category: This is a bug."
- name: "C-docs"
  color: "c1c8ff"
  description: "Category: Improvements or additions to documentation."
- name: "C-enhancement"
  color: "c1c8ff"
  description: "Category: New feature or request."
- name: "C-quality"
  color: "c1c8ff"
  description: "Category: Refactoring, cleanup, and quality improvements."
- name: "C-question"
  color: "c1c8ff"
  description: "Category: Further information is requested."
- name: "E-easy"
  color: "02e10c"
  description:
    "Call for participation: Experience needed to fix: Easy / not much."
- name: "E-medium"
  color: "02e10c"
  description:
    "Call for participation: Experience needed to fix: Medium / intermediate."
- name: "E-hard"
  color: "02e10c"
  description: "Call for participation: Experience needed to fix: Hard / a lot."
- name: "E-help-wanted"
  color: "02e10c"
  description: "Call for participation: Help is requested to fix this issue."
- name: "E-needs-test"
  color: "02e10c"
  description: "Call for participation: Writing correctness tests."
- name: "S-archive"
  color: "d3dddd"
  description: "Status: This pull request exists to archive an unmerged branch."
- name: "S-blocked"
  color: "d3dddd"
  description:
    "Status: Marked as blocked ❌ on something else such as other implementation
    work."
- name: "S-do-not-merge"
  color: "d3dddd"
  description: "Status: This pull request should not be merged."
- name: "S-duplicate"
  color: "d3dddd"
  description: "Status: This issue or pull request already exists."
- name: "S-invalid"
  color: "d3dddd"
  description: "Status: This issue or pull request is not well-formed."
- name: "S-postponed"
  color: "d3dddd"
  description:
    "Status: This issue or pull request is being postponed until later."
- name: "S-speculative"
  color: "d3dddd"
  description: "Status: This is just an idea."
- name: "S-stale"
  color: "d3dddd"
  description:
    "Status: This PR is stale. Please open a new PR if you'd like to pick this
    back up."
- name: "S-wip"
  color: "d3dddd"
  description: "Status: This pull request is a work in progress."
- name: "S-wontfix"
  color: "d3dddd"
  description: "Status: This issue or pull request will not be worked on."
- name: "T-x86_64-unknown-linux-gnu"
  color: "037bfc"
  description: "Target: 64-bit Linux (kernel 2.6.32+, glibc 2.11+)"
- name: "T-x86_64-unknown-linux-musl"
  color: "037bfc"
  description: "Target: 64-bit Linux with MUSL"
- name: "T-aarch64-unknown-linux-gnu"
  color: "037bfc"
  description: "Target: ARM64 Linux (kernel 4.2, glibc 2.17+)"
- name: "T-x86_64-apple-darwin"
  color: "037bfc"
  description: "Target: x86_64 64-bit macOS (10.7+, Lion+)"
- name: "T-aarch64-apple-darwin"
  color: "037bfc"
  description: "Target: ARM64 macOS (11.0+, Big Sur+)"
- name: "T-x86_64-pc-windows-msvc"
  color: "037bfc"
  description: "Target: 64-bit MSVC (Windows 7+)"
- name: "T-x86_64-pc-windows-gnu"
  color: "037bfc"
  description: "Target: 64-bit MinGW (Windows 7+)"
