[project]
name = "artichoke-nightly"
version = "0"
license = {file = "LICENSE"}
classifiers = ["Private :: Do Not Upload"]
dependencies = [
    "stamina>=24.3.0",
    "validators>=0.34.0",
]
requires-python = ">= 3.12"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pyright]
include = [
    "artichoke_nightly",
    "tasks.py",
]
exclude = [
    "**/node_modules",
    "**/__pycache__",
    "**/venv",
    "**/.venv",
]
ignore = []

reportMissingImports = "error"
reportMissingTypeStubs = false

pythonVersion = "3.13"
pythonPlatform = "All"

executionEnvironments = [
  { root = "artichoke_nightly" }
]

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["COM812", "D", "EM", "S603", "T201", "TRY003", "UP007"]

[tool.setuptools.packages.find]
include = ["artichoke_nightly"]
exclude = ["node_modules"]

[dependency-groups]
dev = [
    "invoke>=2.2.0",
    "pyright>=1.1.393",
    "ruff>=0.9.5",
    "types-invoke>=2.0.0.10",
    "types-pyyaml>=6.0.12.20241230",
    "yamllint>=1.35.1",
]
