[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
atomic = true
profile = "black"
line_length = 88
skip_gitignore = true

[tool.mypy]
python_version = "3.11"
strict = true
show_error_codes = true
pretty = true
exclude = [
  "^.git$",
  "^venv$",
]
