---
name: Nightly Builder
"on":
  push:
    tags:
      - "*"
  schedule:
    - cron: "0 0 * * *" # build nightly!
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag
        required: true
      name:
        description: Release name
        required: true

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Get the release version from the tag
        id: release_version
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            release_name="nightly-$(date '+%Y-%m-%d')"
            release_tag="$release_name"
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            release_name=${{ github.event.inputs.name }}
            release_tag=${{ github.event.inputs.tag }}
          else
            release_name="$(basename "${{ github.ref }}")"
            release_tag="$release_name"
          fi
          echo "Release name is: ${release_name}"
          echo "Release version is: ${release_tag}"
          echo "::set-output name=name::${release_name}"
          echo "::set-output name=tag::${release_tag}"

      - name: Clone Artichoke
        uses: actions/checkout@v3
        with:
          repository: artichoke/artichoke
          path: artichoke

      - name: Set latest_commit
        id: latest_commit
        working-directory: artichoke
        run: |
          artichoke_head=$(git rev-parse HEAD)
          echo "Artichoke HEAD commit is: ${artichoke_head}"
          echo "::set-output name=commit::${artichoke_head}"

      - name: Create GitHub release
        id: release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release_version.outputs.tag }}
          draft: true
          prerelease: false
          name: ${{ steps.release_version.outputs.name }}
          body: artichoke/artichoke@${{ steps.latest_commit.outputs.commit }}

      - name: Save release commit hash to artifact
        run: echo "${{ steps.latest_commit.outputs.commit }}" > artifacts/release-commit-hash

      - name: Save release ID to artifact
        run: echo "${{ steps.release.outputs.id }}" > artifacts/release-id

      - name: Save release upload URL to artifact
        run: echo "${{ steps.release.outputs.upload_url }}" > artifacts/release-upload-url

      - name: Save version number to artifact
        run: echo "${{ steps.release_version.outputs.tag }}" > artifacts/release-version

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts

  build-release:
    name: Build Release
    needs: ["create-release"]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        build:
          - linux
          - linux-musl
          - macos
          - macos-apple-silicon
          - windows
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: linux-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
          - build: macos-apple-silicon
            os: macos-11
            target: aarch64-apple-darwin
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get release download URL
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: artifacts

      - name: Set release upload URL and release version
        shell: bash
        id: release_info
        run: |
          release_upload_url="$(cat artifacts/release-upload-url)"
          release_version="$(cat artifacts/release-version)"
          release_commit="$(cat artifacts/release-commit-hash)"

          echo "Release upload url: ${release_upload_url}"
          echo "Release version: ${release_version}"
          echo "Release commit: ${release_commit}"

          echo "::set-output name=upload_url::${release_upload_url}"
          echo "::set-output name=version::${release_version}"
          echo "::set-output name=commit::${release_commit}"

      - name: Generate THIRDPARTY license listing
        id: generate_third_party
        uses: artichoke/generate_third_party@trunk
        with:
          artichoke_ref: ${{ steps.release_info.outputs.commit }}
          target_triple: ${{ matrix.target }}
          output_file: ${{ github.workspace }}/THIRDPARTY.txt

      - name: Clone Artichoke
        uses: actions/checkout@v3
        with:
          repository: artichoke/artichoke
          path: artichoke
          ref: ${{ steps.release_info.outputs.commit }}
          # Fetch all history.
          #
          # The Artichoke release metadata build script calculates Ruby
          # constants like `RUBY_REVISION` by walking the git history.
          fetch-depth: 0

      - name: Setup rust-toolchain override
        shell: bash
        run: cp artichoke/rust-toolchain rust-toolchain

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.target }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # ```
      # $ gpg --fingerprint --with-subkey-fingerprints codesign@artichokeruby.org
      # pub   ed25519 2021-01-03 [SC]
      #       C983 8F10 4021 F59E E6F6  BCBE B199 D034 7FDA 14A4
      # uid           [ultimate] Code signing for Artichoke Ruby <codesign@artichokeruby.org>
      # sub   cv25519 2021-01-03 [E]
      #       7719 1B6D 83B2 F4E8 5197  125B A9A3 F70E 710A 15AA
      # sub   ed25519 2021-01-03 [S]
      #       1C4A 856A CF86 EC1E E841  180F AF57 A37C AC06 1452
      # ```
      - name: Import GPG key
        id: import_gpg
        uses: artichoke/ghaction-import-gpg@v5.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}
          fingerprint: 1C4A856ACF86EC1EE841180FAF57A37CAC061452

      - name: List keys
        run: gpg -K

      - name: Install musl
        if: matrix.build == 'linux-musl'
        run: sudo apt install musl-tools

      - name: Build release artifacts
        working-directory: artichoke
        run: cargo build --verbose --release --target ${{ matrix.target }}

      # This will codesign binaries in place which means that the tarballed
      # binaries will be codesigned as well.
      - name: Run Apple Codesigning and Notarization
        id: apple_codesigning
        if: runner.os == 'macOS'
        run: |
          python3 macos_sign_and_notarize.py "artichoke-nightly-${{ matrix.target }}" \
            --binary artichoke/target/release/artichoke \
            --binary artichoke/target/release/airb \
            --resource artichoke/LICENSE \
            --resource artichoke/README.md \
            --resource THIRDPARTY.txt
        env:
          MACOS_NOTARIZE_APP_PASSWORD: ${{ secrets.MACOS_NOTARIZE_APP_PASSWORD }}
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PASSPHRASE: ${{ secrets.MACOS_CERTIFICATE_PASSPHRASE }}

      - name: GPG sign Apple DMG
        id: apple_codesigning_gpg
        if: runner.os == 'macOS'
        run: |
          python3 gpg_sign.py "artichoke-nightly-${{ matrix.target }}" \
            --artifact "${{ steps.apple_codesigning.outputs.asset }}"

      - name: Upload release archive
        uses: ncipollo/release-action@v1
        if: runner.os == 'macOS'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release_info.outputs.version }}
          draft: true
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          artifacts: ${{ steps.apple_codesigning.outputs.asset }}
          artifactContentType: ${{ steps.apple_codesigning.outputs.content_type }}

      - name: Upload release signature
        uses: ncipollo/release-action@v1
        if: runner.os == 'macOS'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release_info.outputs.version }}
          draft: true
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          artifacts: ${{ steps.apple_codesigning_gpg.outputs.signature }}
          artifactContentType: "text/plain"

      - name: Build archive
        shell: bash
        id: build
        run: |
          staging="artichoke-nightly-${{ matrix.target }}"
          mkdir -p "$staging"/
          cp artichoke/{README.md,LICENSE} THIRDPARTY.txt "$staging/"
          if [ "${{ runner.os }}" = "Windows" ]; then
            cp "artichoke/target/${{ matrix.target }}/release/artichoke.exe" "$staging/"
            cp "artichoke/target/${{ matrix.target }}/release/airb.exe" "$staging/"
            7z a "$staging.zip" "$staging"
            echo "::set-output name=asset::$staging.zip"
            echo "::set-output name=content_type::application/zip"
          else
            cp "artichoke/target/${{ matrix.target }}/release/artichoke" "$staging/"
            cp "artichoke/target/${{ matrix.target }}/release/airb" "$staging/"
            tar czf "$staging.tar.gz" "$staging"
            echo "::set-output name=asset::$staging.tar.gz"
            echo "::set-output name=content_type::application/gzip"
          fi

      - name: GPG sign archive
        id: gpg_signing
        run: python3 gpg_sign.py "artichoke-nightly-${{ matrix.target }}" --artifact "${{ steps.build.outputs.asset }}"

      - name: Upload release archive
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release_info.outputs.version }}
          draft: true
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          artifacts: ${{ steps.build.outputs.asset }}
          artifactContentType: ${{ steps.build.outputs.content_type }}

      - name: Upload release signature
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release_info.outputs.version }}
          draft: true
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          artifacts: ${{ steps.gpg_signing.outputs.signature }}
          artifactContentType: "text/plain"

  finalize-release:
    name: Publish Release
    needs: ["build-release"]
    runs-on: ubuntu-latest
    steps:
      - name: Get release download URL
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: artifacts

      - name: Set publish_info
        id: publish_info
        run: echo "::set-output name=release_tag::$(cat artifacts/release-version)"

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.publish_info.outputs.release_tag }}
          draft: false
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true

      - uses: eregon/keep-last-n-releases@v1
        if: github.event_name == 'schedule'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          n: 7
